# Generated by Django 5.2.6 on 2025-11-12 01:47

import django.db.models.deletion
import food_record.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FoodRecord",
            fields=[
                ("record_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=food_record.models.food_image_upload_path,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("calories", models.FloatField(blank=True, null=True)),
                ("nutrients", models.JSONField(blank=True, null=True)),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recorded_by",
                    models.ForeignKey(
                        db_column="id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="food_records",
                        to="users.userprofile",
                    ),
                ),
            ],
        ),
    ]
