# Generated by Django 5.2.6 on 2025-11-17 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analysis', '0001_initial'),
        ('food_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionresult',
            name='user',
        ),
        migrations.CreateModel(
            name='FoodAnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_food', models.CharField(max_length=100)),
                ('confidence', models.FloatField()),
                ('nutrients', models.JSONField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='food_record.foodrecord')),
            ],
        ),
        migrations.DeleteModel(
            name='FoodSuggestion',
        ),
        migrations.DeleteModel(
            name='RecognitionResult',
        ),
    ]
