# Generated by Django 5.2.6 on 2025-11-06 06:47

import django.db.models.deletion
import django.utils.timezone
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthAccount',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='ログインに使用するメールアドレス', max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': '認証アカウント',
                'verbose_name_plural': '認証アカウント',
                'db_table': 'auth_account',
            },
            managers=[
                ('objects', users.models.AuthAccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_status', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '初回登録ステータス',
                'verbose_name_plural': '初回登録ステータス',
                'db_table': 'onboarding_status',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=users.models.avatar_upload_path)),
                ('display_name', models.CharField(blank=True, help_text='アプリ内で表示される名前（ニックネーム）', max_length=80)),
                ('bio', models.TextField(blank=True, default='', help_text='自己紹介')),
                ('height_cm', models.DecimalField(blank=True, decimal_places=2, help_text='身長(cm)', max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, help_text='体重(kg)', max_digits=5, null=True)),
                ('daily_kcal', models.PositiveIntegerField(default=2000, help_text='1日の目標摂取カロリー(kcal)')),
                ('target_weight', models.PositiveBigIntegerField(default=0, help_text='目標体重の設定(kg)')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ユーザープロフィール',
                'verbose_name_plural': 'ユーザープロフィール',
                'db_table': 'user_profile',
            },
        ),
    ]
