# Generated by Django 5.2.6 on 2025-11-06 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_eaten', models.DateField(blank=True, null=True)),
                ('time_eaten', models.CharField(blank=True, choices=[('朝食', 'Breakfast'), ('昼食', 'Lunch'), ('夕食', 'Dinner'), ('間食', 'Snack'), ('その他', 'Other')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='meals/')),
                ('memo', models.TextField(blank=True, null=True)),
                ('calorie', models.IntegerField()),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_eaten', models.DateField(blank=True, null=True)),
                ('time_eaten', models.CharField(blank=True, choices=[('朝食', 'Breakfast'), ('昼食', 'Lunch'), ('夕食', 'Dinner'), ('間食', 'Snack'), ('その他', 'Other')], max_length=255, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('meals', models.ManyToManyField(related_name='dishes', to='core.meal')),
            ],
        ),
    ]
