# Generated by Django 5.2.6 on 2025-10-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='datetime_eaten',
        ),
        migrations.AddField(
            model_name='meal',
            name='time_eaten',
            field=models.CharField(blank=True, choices=[('朝食', 'Breakfast'), ('昼食', 'Lunch'), ('夕食', 'Dinner'), ('間食', 'Snack'), ('その他', 'Other')], max_length=255, null=True),
        ),
    ]
